from pathlib import Path

lines = []
lines.append('<!DOCTYPE html>')
lines.append('<html lang="fr" data-theme="light">')
lines.append('<head>')
lines.append('  <meta charset="utf-8" />')
lines.append('  <meta name="viewport" content="width=device-width, initial-scale=1" />')
lines.append('  <title>Assistant de cours</title>')
lines.append('  <link rel="manifest" href="./manifest.webmanifest" />')
lines.append('  <link rel="stylesheet" href="./theme.css" />')
lines.append('  <link rel="stylesheet" href="./icons.css" />')
lines.append('  <link rel="stylesheet" href="./app.css" />')
lines.append('</head>')
lines.append('<body>')
lines.append('  <a class="skip-link" href="#main-content">Aller au contenu</a>')
lines.append('  <header class="app-header" role="banner">')
lines.append('    <div class="header-brand">')
lines.append('      <div class="logo css-icon css-icon--brain" aria-hidden="true"></div>')
lines.append('      <div>')
lines.append('        <h1 id="app-title">Assistant de cours</h1>')
lines.append('        <p class="tagline">Capturez, structurez et révisez chaque cours avec élégance.</p>')
lines.append('      </div>')
lines.append('    </div>')
lines.append('    <div class="header-actions">')
lines.append('      <div class="lang-switcher" aria-label="Choisir la langue">')
lines.append('        <label for="lang-select">Langue</label>')
lines.append('        <select id="lang-select" aria-controls="app-title">')
lines.append('          <option value="fr-FR" selected>Français</option>')
lines.append('          <option value="en-US">English</option>')
lines.append('        </select>')
lines.append('      </div>')
lines.append('      <button class="theme-toggle" id="theme-toggle" role="switch" aria-checked="false">')
lines.append('        <span class="css-icon css-icon--sun" aria-hidden="true"></span>')
lines.append('        <span class="theme-toggle__label">Mode clair</span>')
lines.append('      </button>')
lines.append('    </div>')
lines.append('  </header>')
lines.append('  <div class="layout">')
lines.append('    <aside class="sidebar" aria-label="Navigation des matières">')
lines.append('      <nav class="sidebar-nav">')
lines.append('        <h2>Matières</h2>')
lines.append('        <button class="sidebar__add" id="add-section-btn">+ Ajouter une section</button>')
subjects = [
    ('Mathématiques', 'Explorations analytiques et algébriques'),
    ('Physique', 'Expériences et théories contemporaines'),
    ('Histoire', 'Chronologies et perspectives critiques'),
    ('Droit', 'Études de cas et jurisprudence'),
    ('Biologie', 'Systèmes vivants et écologie'),
    ('Informatique', 'Algorithmique et génie logiciel'),
    ('Économie', 'Modèles et marchés mondiaux'),
    ('Philosophie', 'Concepts et argumentations'),
]
for subject in subjects:
    lines.append('        <div class="sidebar-section">')
    lines.append(f'          <button class="sidebar-section__title" data-section="{subject[0]}">{subject[0]}</button>')
    lines.append(f'          <p class="sidebar-section__desc">{subject[1]}</p>')
    lines.append('        </div>')
lines.append('      </nav>')
lines.append('      <footer class="sidebar-footer">')
lines.append('        <p>Progression hebdomadaire</p>')
lines.append('        <div class="progress-grid" role="list">')
for week in range(1, 13):
    lines.append(f'          <div role="listitem" class="progress-card">Semaine {week}</div>')
lines.append('        </div>')
lines.append('      </footer>')
lines.append('    </aside>')
lines.append('    <main id="main-content" class="main-content" role="main">')
lines.append('      <section class="hero" aria-label="Actions principales">')
lines.append('        <div class="hero-actions">')
lines.append('          <button class="cta cta--primary" id="record-btn">')
lines.append('            <span class="css-icon css-icon--micro" aria-hidden="true"></span>')
lines.append('            <span>Enregistrer un cours</span>')
lines.append('          </button>')
lines.append('          <button class="cta cta--secondary" id="import-btn">')
lines.append('            <span class="css-icon css-icon--upload" aria-hidden="true"></span>')
lines.append('            <span>Importer un audio</span>')
lines.append('          </button>')
lines.append('        </div>')
lines.append('        <p class="hero-description">Utilisez l\'assistant pour créer des transcriptions précises, générer des synthèses et concevoir des outils d\'étude adaptés.</p>')
lines.append('      </section>')
lines.append('      <section class="dashboard">')
lines.append('        <h2>Sessions récentes</h2>')
for idx in range(1, 41):
    lines.append(f'        <article class="session-card session-card--math" data-session="math-{idx}">')
    lines.append('          <header class="session-card__header">')
    lines.append(f'            <h3>Analyse des séries {idx}</h3>')
    lines.append('            <span class="session-card__status">En cours</span>')
    lines.append('          </header>')
    lines.append('          <p class="session-card__summary">Étude des méthodes de convergence, comparaison, séries de Fourier et applications pédagogiques aux problèmes réels.</p>')
    lines.append('          <dl class="session-card__meta">')
    lines.append('            <div>')
    lines.append('              <dt>Durée</dt>')
    lines.append(f'              <dd>{45 + idx} minutes</dd>')
    lines.append('            </div>')
    lines.append('            <div>')
    lines.append('              <dt>Dernière mise à jour</dt>')
    lines.append(f'              <dd>2024-03-{(idx % 28) + 1:02d}</dd>')
    lines.append('            </div>')
    lines.append('            <div>')
    lines.append('              <dt>Marqueurs</dt>')
    lines.append('              <dd>Définition, Théorème, Exemple</dd>')
    lines.append('            </div>')
    lines.append('          </dl>')
    lines.append('          <footer class="session-card__footer">')
    lines.append('            <button class="btn btn--ghost">Ouvrir</button>')
    lines.append('            <button class="btn btn--ghost">Partager</button>')
    lines.append('            <button class="btn btn--ghost">Exporter</button>')
    lines.append('          </footer>')
    lines.append('        </article>')
lines.append('      </section>')
lines.append('      <section class="live-transcription" aria-live="polite">')
lines.append('        <header class="panel-header">')
lines.append('          <h2>Transcription en direct</h2>')
lines.append('          <div class="panel-controls">')
lines.append('            <button class="btn btn--icon" id="marker-definition">Définition</button>')
lines.append('            <button class="btn btn--icon" id="marker-example">Exemple</button>')
lines.append('            <button class="btn btn--icon" id="marker-theorem">Théorème</button>')
lines.append('            <button class="btn btn--icon" id="marker-important">Important</button>')
lines.append('          </div>')
lines.append('        </header>')
lines.append('        <div class="transcription-display" id="transcription-stream">')
for line in range(1, 201):
    lines.append(f'          <p class="transcription-line" data-time="00:{line:02d}:00"><span class="timestamp">[00:{line:02d}:00]</span> Contenu pédagogique structuré {line}, mettant en avant une démonstration détaillée et des liens interdisciplinaires.</p>')
lines.append('        </div>')
lines.append('        <div class="transcription-actions">')
lines.append('          <button class="btn btn--primary" id="download-transcript">Télécharger .txt</button>')
lines.append('          <button class="btn btn--secondary" id="clean-transcript">Nettoyer</button>')
lines.append('          <button class="btn btn--secondary" id="save-session">Sauvegarder la session</button>')
lines.append('        </div>')
lines.append('      </section>')
panels = [
    ('Synthèse IA', 'résumé global avec sections structurées'),
    ('Plan détaillé', 'plan hiérarchique utilisable pour la révision'),
    ('Glossaire', 'terminologie essentielle à retenir'),
    ('QCM généré', 'questions à choix multiples variées'),
    ('Textes à trous', 'phrases à compléter pour mémorisation'),
    ('Flashcards Leitner', 'cartes recto verso pour révisions espacées'),
]
for panel in panels:
    lines.append('      <section class="ai-panel">')
    lines.append(f'        <header class="panel-header"><h2>{panel[0]}</h2><p>{panel[1]}</p></header>')
    lines.append('        <div class="ai-panel__content">')
    for i in range(1, 31):
        lines.append(f'          <article class="ai-block ai-block--{i % 5}">')
        lines.append(f'            <h3>{panel[0]} bloc {i}</h3>')
        lines.append('            <p>Explications approfondies sur les notions clés, analogies pratiques et recommandations de lecture complémentaire.</p>')
        lines.append('            <ul>')
        lines.append('              <li>Méthode pédagogique progressive</li>')
        lines.append('              <li>Exemple contextualisé</li>')
        lines.append('              <li>Référence bibliographique</li>')
        lines.append('            </ul>')
        lines.append('          </article>')
    lines.append('        </div>')
    lines.append('      </section>')
lines.append('      <section class="session-detail">')
lines.append('        <header class="panel-header">')
lines.append('          <h2>Détail de session</h2>')
lines.append('          <nav class="tabs" role="tablist">')
tabs = ['Transcription', 'Résumé', 'Quiz', 'Flashcards']
for tab in tabs:
    lines.append(f'            <button role="tab" class="tab" aria-controls="tab-{tab.lower()}">{tab}</button>')
lines.append('          </nav>')
lines.append('        </header>')
for tab in ['transcription', 'resume', 'quiz', 'flashcards']:
    lines.append(f'        <div id="tab-{tab}" role="tabpanel" class="tab-panel">')
    for item in range(1, 41):
        lines.append(f'          <p><strong>Élément {item}</strong> — Description structurée pour {tab} avec démonstrations, applications et rappels méthodologiques.</p>')
    lines.append('        </div>')
lines.append('      </section>')
lines.append('      <section class="flashcards-gallery">')
lines.append('        <h2>Flashcards de démonstration</h2>')
lines.append('        <div class="flashcards-grid">')
for i in range(1, 61):
    lines.append('          <article class="flashcard" tabindex="0">')
    lines.append(f'            <h3>Carte {i}</h3>')
    lines.append('            <p class="flashcard__front">Concept clef exposé avec précision.</p>')
    lines.append('            <p class="flashcard__back">Explication détaillée, exemples transversaux et conseil de mémorisation.</p>')
    lines.append('            <footer class="flashcard__meta">')
    lines.append('              <span>Boîte 1</span>')
    lines.append('              <span>Due demain</span>')
    lines.append('            </footer>')
    lines.append('          </article>')
lines.append('        </div>')
lines.append('      </section>')
lines.append('      <section class="quiz-section">')
lines.append('        <h2>QCM interactifs</h2>')
for q in range(1, 31):
    lines.append('        <article class="quiz-card">')
    lines.append(f'          <h3>Question {q}</h3>')
    lines.append('          <p>Déterminez la réponse la plus adaptée au contexte pédagogique présenté.</p>')
    lines.append('          <ol class="quiz-choices">')
    for choice in ['Option A', 'Option B', 'Option C', 'Option D']:
        lines.append(f'            <li>{choice}</li>')
    lines.append('          </ol>')
    lines.append('          <p class="quiz-explanation">Explication détaillée fournissant un retour immédiat et des pistes de révision.</p>')
    lines.append('        </article>')
lines.append('      </section>')
lines.append('      <section class="study-timeline">')
lines.append('        <h2>Chronologie des révisions</h2>')
lines.append('        <ol class="timeline">')
for day in range(1, 91):
    lines.append(f'          <li class="timeline__event">Jour {day} — Activités de consolidation, lecture conseillée et exercices corrigés.</li>')
lines.append('        </ol>')
lines.append('      </section>')
lines.append('      <footer class="app-footer" role="contentinfo">')
lines.append('        <div class="footer-columns">')
for column in range(1, 11):
    lines.append('          <div class="footer-column">')
    lines.append(f'            <h3>Ressources {column}</h3>')
    lines.append('            <ul>')
    for item in range(1, 21):
        lines.append(f'              <li><a href="#">Lien pédagogique {column}.{item}</a></li>')
    lines.append('            </ul>')
    lines.append('          </div>')
lines.append('        </div>')
lines.append('        <p class="footer-copy">© 2024 Assistant de cours — Plateforme d\'apprentissage accessible.</p>')
lines.append('      </footer>')
lines.append('    </main>')
lines.append('  </div>')
lines.append('  <dialog id="import-dialog" class="modal" aria-labelledby="import-title">')
lines.append('    <h2 id="import-title">Importer un fichier audio</h2>')
lines.append('    <form id="import-form">')
lines.append('      <label for="audio-file">Choisir un fichier</label>')
lines.append('      <input type="file" id="audio-file" accept="audio/mpeg,audio/wav,audio/webm" />')
lines.append('      <button type="submit" class="btn btn--primary">Lancer le traitement</button>')
lines.append('      <button type="button" class="btn btn--secondary" data-close>Annuler</button>')
lines.append('    </form>')
lines.append('  </dialog>')
lines.append('  <dialog id="ai-dialog" class="modal" aria-labelledby="ai-title">')
lines.append('    <h2 id="ai-title">Génération IA</h2>')
lines.append('    <div class="modal-content">')
for block in range(1, 61):
    lines.append('      <section class="modal-section">')
    lines.append(f'        <h3>Bloc analytique {block}</h3>')
    lines.append('        <p>Ce bloc détaille une approche pédagogique spécifique, comprend des points de vigilance et des suggestions d\'exercices.</p>')
    lines.append('      </section>')
lines.append('    </div>')
lines.append('    <button class="btn btn--primary" data-close>Fermer</button>')
lines.append('  </dialog>')
lines.append('  <script type="module" src="./app.js"></script>')
lines.append('</body>')
lines.append('</html>')
Path('public/index.html').write_text('\n'.join(lines))
print('Total lines', len(lines))
